// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/devices/device.proto

package lightspeed.devices;

public final class Device {
  private Device() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoDeviceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lightspeed.devices.ProtoDevice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .lightspeed.props.Property properties = 3;</code>
     */
    java.util.List<lightspeed.props.Props.Property> 
        getPropertiesList();
    /**
     * <code>repeated .lightspeed.props.Property properties = 3;</code>
     */
    lightspeed.props.Props.Property getProperties(int index);
    /**
     * <code>repeated .lightspeed.props.Property properties = 3;</code>
     */
    int getPropertiesCount();
    /**
     * <code>repeated .lightspeed.props.Property properties = 3;</code>
     */
    java.util.List<? extends lightspeed.props.Props.PropertyOrBuilder> 
        getPropertiesOrBuilderList();
    /**
     * <code>repeated .lightspeed.props.Property properties = 3;</code>
     */
    lightspeed.props.Props.PropertyOrBuilder getPropertiesOrBuilder(
        int index);

    /**
     * <code>string address = 4;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 4;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>int32 baud = 5;</code>
     * @return The baud.
     */
    int getBaud();

    /**
     * <code>.lightspeed.devices.ProtoDevice.Family family = 6;</code>
     * @return The enum numeric value on the wire for family.
     */
    int getFamilyValue();
    /**
     * <code>.lightspeed.devices.ProtoDevice.Family family = 6;</code>
     * @return The family.
     */
    lightspeed.devices.Device.ProtoDevice.Family getFamily();
  }
  /**
   * Protobuf type {@code lightspeed.devices.ProtoDevice}
   */
  public static final class ProtoDevice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lightspeed.devices.ProtoDevice)
      ProtoDeviceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoDevice.newBuilder() to construct.
    private ProtoDevice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoDevice() {
      id_ = "";
      name_ = "";
      properties_ = java.util.Collections.emptyList();
      address_ = "";
      family_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtoDevice();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoDevice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                properties_ = new java.util.ArrayList<lightspeed.props.Props.Property>();
                mutable_bitField0_ |= 0x00000001;
              }
              properties_.add(
                  input.readMessage(lightspeed.props.Props.Property.parser(), extensionRegistry));
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 40: {

              baud_ = input.readInt32();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              family_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          properties_ = java.util.Collections.unmodifiableList(properties_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lightspeed.devices.Device.internal_static_lightspeed_devices_ProtoDevice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lightspeed.devices.Device.internal_static_lightspeed_devices_ProtoDevice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lightspeed.devices.Device.ProtoDevice.class, lightspeed.devices.Device.ProtoDevice.Builder.class);
    }

    /**
     * Protobuf enum {@code lightspeed.devices.ProtoDevice.Family}
     */
    public enum Family
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CCD = 0;</code>
       */
      CCD(0),
      /**
       * <code>MOUNT = 1;</code>
       */
      MOUNT(1),
      /**
       * <code>FOCUSER = 2;</code>
       */
      FOCUSER(2),
      /**
       * <code>FILTER_WHEEL = 3;</code>
       */
      FILTER_WHEEL(3),
      /**
       * <code>POWER_BOX = 4;</code>
       */
      POWER_BOX(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CCD = 0;</code>
       */
      public static final int CCD_VALUE = 0;
      /**
       * <code>MOUNT = 1;</code>
       */
      public static final int MOUNT_VALUE = 1;
      /**
       * <code>FOCUSER = 2;</code>
       */
      public static final int FOCUSER_VALUE = 2;
      /**
       * <code>FILTER_WHEEL = 3;</code>
       */
      public static final int FILTER_WHEEL_VALUE = 3;
      /**
       * <code>POWER_BOX = 4;</code>
       */
      public static final int POWER_BOX_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Family valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Family forNumber(int value) {
        switch (value) {
          case 0: return CCD;
          case 1: return MOUNT;
          case 2: return FOCUSER;
          case 3: return FILTER_WHEEL;
          case 4: return POWER_BOX;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Family>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Family> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Family>() {
              public Family findValueByNumber(int number) {
                return Family.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return lightspeed.devices.Device.ProtoDevice.getDescriptor().getEnumTypes().get(0);
      }

      private static final Family[] VALUES = values();

      public static Family valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Family(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:lightspeed.devices.ProtoDevice.Family)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROPERTIES_FIELD_NUMBER = 3;
    private java.util.List<lightspeed.props.Props.Property> properties_;
    /**
     * <code>repeated .lightspeed.props.Property properties = 3;</code>
     */
    @java.lang.Override
    public java.util.List<lightspeed.props.Props.Property> getPropertiesList() {
      return properties_;
    }
    /**
     * <code>repeated .lightspeed.props.Property properties = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends lightspeed.props.Props.PropertyOrBuilder> 
        getPropertiesOrBuilderList() {
      return properties_;
    }
    /**
     * <code>repeated .lightspeed.props.Property properties = 3;</code>
     */
    @java.lang.Override
    public int getPropertiesCount() {
      return properties_.size();
    }
    /**
     * <code>repeated .lightspeed.props.Property properties = 3;</code>
     */
    @java.lang.Override
    public lightspeed.props.Props.Property getProperties(int index) {
      return properties_.get(index);
    }
    /**
     * <code>repeated .lightspeed.props.Property properties = 3;</code>
     */
    @java.lang.Override
    public lightspeed.props.Props.PropertyOrBuilder getPropertiesOrBuilder(
        int index) {
      return properties_.get(index);
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 4;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 4;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BAUD_FIELD_NUMBER = 5;
    private int baud_;
    /**
     * <code>int32 baud = 5;</code>
     * @return The baud.
     */
    @java.lang.Override
    public int getBaud() {
      return baud_;
    }

    public static final int FAMILY_FIELD_NUMBER = 6;
    private int family_;
    /**
     * <code>.lightspeed.devices.ProtoDevice.Family family = 6;</code>
     * @return The enum numeric value on the wire for family.
     */
    @java.lang.Override public int getFamilyValue() {
      return family_;
    }
    /**
     * <code>.lightspeed.devices.ProtoDevice.Family family = 6;</code>
     * @return The family.
     */
    @java.lang.Override public lightspeed.devices.Device.ProtoDevice.Family getFamily() {
      @SuppressWarnings("deprecation")
      lightspeed.devices.Device.ProtoDevice.Family result = lightspeed.devices.Device.ProtoDevice.Family.valueOf(family_);
      return result == null ? lightspeed.devices.Device.ProtoDevice.Family.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        output.writeMessage(3, properties_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, address_);
      }
      if (baud_ != 0) {
        output.writeInt32(5, baud_);
      }
      if (family_ != lightspeed.devices.Device.ProtoDevice.Family.CCD.getNumber()) {
        output.writeEnum(6, family_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, properties_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, address_);
      }
      if (baud_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, baud_);
      }
      if (family_ != lightspeed.devices.Device.ProtoDevice.Family.CCD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, family_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lightspeed.devices.Device.ProtoDevice)) {
        return super.equals(obj);
      }
      lightspeed.devices.Device.ProtoDevice other = (lightspeed.devices.Device.ProtoDevice) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getPropertiesList()
          .equals(other.getPropertiesList())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (getBaud()
          != other.getBaud()) return false;
      if (family_ != other.family_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getPropertiesCount() > 0) {
        hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
        hash = (53 * hash) + getPropertiesList().hashCode();
      }
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + BAUD_FIELD_NUMBER;
      hash = (53 * hash) + getBaud();
      hash = (37 * hash) + FAMILY_FIELD_NUMBER;
      hash = (53 * hash) + family_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lightspeed.devices.Device.ProtoDevice parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lightspeed.devices.Device.ProtoDevice parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lightspeed.devices.Device.ProtoDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lightspeed.devices.Device.ProtoDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lightspeed.devices.Device.ProtoDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lightspeed.devices.Device.ProtoDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lightspeed.devices.Device.ProtoDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lightspeed.devices.Device.ProtoDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static lightspeed.devices.Device.ProtoDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static lightspeed.devices.Device.ProtoDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lightspeed.devices.Device.ProtoDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lightspeed.devices.Device.ProtoDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lightspeed.devices.Device.ProtoDevice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lightspeed.devices.ProtoDevice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lightspeed.devices.ProtoDevice)
        lightspeed.devices.Device.ProtoDeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lightspeed.devices.Device.internal_static_lightspeed_devices_ProtoDevice_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lightspeed.devices.Device.internal_static_lightspeed_devices_ProtoDevice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lightspeed.devices.Device.ProtoDevice.class, lightspeed.devices.Device.ProtoDevice.Builder.class);
      }

      // Construct using lightspeed.devices.Device.ProtoDevice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPropertiesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          propertiesBuilder_.clear();
        }
        address_ = "";

        baud_ = 0;

        family_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lightspeed.devices.Device.internal_static_lightspeed_devices_ProtoDevice_descriptor;
      }

      @java.lang.Override
      public lightspeed.devices.Device.ProtoDevice getDefaultInstanceForType() {
        return lightspeed.devices.Device.ProtoDevice.getDefaultInstance();
      }

      @java.lang.Override
      public lightspeed.devices.Device.ProtoDevice build() {
        lightspeed.devices.Device.ProtoDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lightspeed.devices.Device.ProtoDevice buildPartial() {
        lightspeed.devices.Device.ProtoDevice result = new lightspeed.devices.Device.ProtoDevice(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        if (propertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            properties_ = java.util.Collections.unmodifiableList(properties_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.properties_ = properties_;
        } else {
          result.properties_ = propertiesBuilder_.build();
        }
        result.address_ = address_;
        result.baud_ = baud_;
        result.family_ = family_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lightspeed.devices.Device.ProtoDevice) {
          return mergeFrom((lightspeed.devices.Device.ProtoDevice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lightspeed.devices.Device.ProtoDevice other) {
        if (other == lightspeed.devices.Device.ProtoDevice.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (propertiesBuilder_ == null) {
          if (!other.properties_.isEmpty()) {
            if (properties_.isEmpty()) {
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePropertiesIsMutable();
              properties_.addAll(other.properties_);
            }
            onChanged();
          }
        } else {
          if (!other.properties_.isEmpty()) {
            if (propertiesBuilder_.isEmpty()) {
              propertiesBuilder_.dispose();
              propertiesBuilder_ = null;
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000001);
              propertiesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPropertiesFieldBuilder() : null;
            } else {
              propertiesBuilder_.addAllMessages(other.properties_);
            }
          }
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.getBaud() != 0) {
          setBaud(other.getBaud());
        }
        if (other.family_ != 0) {
          setFamilyValue(other.getFamilyValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        lightspeed.devices.Device.ProtoDevice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (lightspeed.devices.Device.ProtoDevice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<lightspeed.props.Props.Property> properties_ =
        java.util.Collections.emptyList();
      private void ensurePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          properties_ = new java.util.ArrayList<lightspeed.props.Props.Property>(properties_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          lightspeed.props.Props.Property, lightspeed.props.Props.Property.Builder, lightspeed.props.Props.PropertyOrBuilder> propertiesBuilder_;

      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public java.util.List<lightspeed.props.Props.Property> getPropertiesList() {
        if (propertiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(properties_);
        } else {
          return propertiesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public int getPropertiesCount() {
        if (propertiesBuilder_ == null) {
          return properties_.size();
        } else {
          return propertiesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public lightspeed.props.Props.Property getProperties(int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);
        } else {
          return propertiesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public Builder setProperties(
          int index, lightspeed.props.Props.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.set(index, value);
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public Builder setProperties(
          int index, lightspeed.props.Props.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public Builder addProperties(lightspeed.props.Props.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public Builder addProperties(
          int index, lightspeed.props.Props.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(index, value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public Builder addProperties(
          lightspeed.props.Props.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public Builder addProperties(
          int index, lightspeed.props.Props.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public Builder addAllProperties(
          java.lang.Iterable<? extends lightspeed.props.Props.Property> values) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, properties_);
          onChanged();
        } else {
          propertiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public Builder clearProperties() {
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public Builder removeProperties(int index) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.remove(index);
          onChanged();
        } else {
          propertiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public lightspeed.props.Props.Property.Builder getPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public lightspeed.props.Props.PropertyOrBuilder getPropertiesOrBuilder(
          int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);  } else {
          return propertiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public java.util.List<? extends lightspeed.props.Props.PropertyOrBuilder> 
           getPropertiesOrBuilderList() {
        if (propertiesBuilder_ != null) {
          return propertiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(properties_);
        }
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public lightspeed.props.Props.Property.Builder addPropertiesBuilder() {
        return getPropertiesFieldBuilder().addBuilder(
            lightspeed.props.Props.Property.getDefaultInstance());
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public lightspeed.props.Props.Property.Builder addPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().addBuilder(
            index, lightspeed.props.Props.Property.getDefaultInstance());
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 3;</code>
       */
      public java.util.List<lightspeed.props.Props.Property.Builder> 
           getPropertiesBuilderList() {
        return getPropertiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          lightspeed.props.Props.Property, lightspeed.props.Props.Property.Builder, lightspeed.props.Props.PropertyOrBuilder> 
          getPropertiesFieldBuilder() {
        if (propertiesBuilder_ == null) {
          propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              lightspeed.props.Props.Property, lightspeed.props.Props.Property.Builder, lightspeed.props.Props.PropertyOrBuilder>(
                  properties_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          properties_ = null;
        }
        return propertiesBuilder_;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 4;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 4;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 4;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 4;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private int baud_ ;
      /**
       * <code>int32 baud = 5;</code>
       * @return The baud.
       */
      @java.lang.Override
      public int getBaud() {
        return baud_;
      }
      /**
       * <code>int32 baud = 5;</code>
       * @param value The baud to set.
       * @return This builder for chaining.
       */
      public Builder setBaud(int value) {
        
        baud_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 baud = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaud() {
        
        baud_ = 0;
        onChanged();
        return this;
      }

      private int family_ = 0;
      /**
       * <code>.lightspeed.devices.ProtoDevice.Family family = 6;</code>
       * @return The enum numeric value on the wire for family.
       */
      @java.lang.Override public int getFamilyValue() {
        return family_;
      }
      /**
       * <code>.lightspeed.devices.ProtoDevice.Family family = 6;</code>
       * @param value The enum numeric value on the wire for family to set.
       * @return This builder for chaining.
       */
      public Builder setFamilyValue(int value) {
        
        family_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.lightspeed.devices.ProtoDevice.Family family = 6;</code>
       * @return The family.
       */
      @java.lang.Override
      public lightspeed.devices.Device.ProtoDevice.Family getFamily() {
        @SuppressWarnings("deprecation")
        lightspeed.devices.Device.ProtoDevice.Family result = lightspeed.devices.Device.ProtoDevice.Family.valueOf(family_);
        return result == null ? lightspeed.devices.Device.ProtoDevice.Family.UNRECOGNIZED : result;
      }
      /**
       * <code>.lightspeed.devices.ProtoDevice.Family family = 6;</code>
       * @param value The family to set.
       * @return This builder for chaining.
       */
      public Builder setFamily(lightspeed.devices.Device.ProtoDevice.Family value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        family_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.lightspeed.devices.ProtoDevice.Family family = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFamily() {
        
        family_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lightspeed.devices.ProtoDevice)
    }

    // @@protoc_insertion_point(class_scope:lightspeed.devices.ProtoDevice)
    private static final lightspeed.devices.Device.ProtoDevice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lightspeed.devices.Device.ProtoDevice();
    }

    public static lightspeed.devices.Device.ProtoDevice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoDevice>
        PARSER = new com.google.protobuf.AbstractParser<ProtoDevice>() {
      @java.lang.Override
      public ProtoDevice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoDevice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoDevice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoDevice> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lightspeed.devices.Device.ProtoDevice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightspeed_devices_ProtoDevice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightspeed_devices_ProtoDevice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035protocol/devices/device.proto\022\022lightsp" +
      "eed.devices\032\037protocol/properties/props.p" +
      "roto\"\372\001\n\013ProtoDevice\022\n\n\002id\030\001 \001(\t\022\014\n\004name" +
      "\030\002 \001(\t\022.\n\nproperties\030\003 \003(\0132\032.lightspeed." +
      "props.Property\022\017\n\007address\030\004 \001(\t\022\014\n\004baud\030" +
      "\005 \001(\005\0226\n\006family\030\006 \001(\0162&.lightspeed.devic" +
      "es.ProtoDevice.Family\"J\n\006Family\022\007\n\003CCD\020\000" +
      "\022\t\n\005MOUNT\020\001\022\013\n\007FOCUSER\020\002\022\020\n\014FILTER_WHEEL" +
      "\020\003\022\r\n\tPOWER_BOX\020\004P\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          lightspeed.props.Props.getDescriptor(),
        });
    internal_static_lightspeed_devices_ProtoDevice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightspeed_devices_ProtoDevice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightspeed_devices_ProtoDevice_descriptor,
        new java.lang.String[] { "Id", "Name", "Properties", "Address", "Baud", "Family", });
    lightspeed.props.Props.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
