[package]
name = "lightspeed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lightspeed"
path = "src/lib.rs"

[dependencies]
protoc-bin-vendored = "3"
protobuf-codegen = "3.0.2"
protobuf = "3.0.2"

[build-dependencies]
protoc-bin-vendored = "3"
protobuf-codegen = "3.0.2"
protobuf = "3.0.2"