[package]
name = "lightspeed"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lightspeed"
path = "src/lib.rs"

[dependencies]
protobuf = "3.0"
prost = "0.10"
tonic = "0.7"

[build-dependencies]
protoc-bin-vendored = "3"
protobuf-codegen = "3.0"
protobuf = "3.0"
tonic-build = "0.7"