// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/devices/device.proto

#include "protocol/devices/device.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace lightspeed {
namespace devices {
PROTOBUF_CONSTEXPR ProtoDevice::ProtoDevice(
    ::_pbi::ConstantInitialized)
  : properties_()
  , id_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , name_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , address_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , baud_(0)
  , family_(0)
{}
struct ProtoDeviceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtoDeviceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtoDeviceDefaultTypeInternal() {}
  union {
    ProtoDevice _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtoDeviceDefaultTypeInternal _ProtoDevice_default_instance_;
}  // namespace devices
}  // namespace lightspeed
static ::_pb::Metadata file_level_metadata_protocol_2fdevices_2fdevice_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_protocol_2fdevices_2fdevice_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_protocol_2fdevices_2fdevice_2eproto = nullptr;

const uint32_t TableStruct_protocol_2fdevices_2fdevice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lightspeed::devices::ProtoDevice, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lightspeed::devices::ProtoDevice, id_),
  PROTOBUF_FIELD_OFFSET(::lightspeed::devices::ProtoDevice, name_),
  PROTOBUF_FIELD_OFFSET(::lightspeed::devices::ProtoDevice, properties_),
  PROTOBUF_FIELD_OFFSET(::lightspeed::devices::ProtoDevice, address_),
  PROTOBUF_FIELD_OFFSET(::lightspeed::devices::ProtoDevice, baud_),
  PROTOBUF_FIELD_OFFSET(::lightspeed::devices::ProtoDevice, family_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::lightspeed::devices::ProtoDevice)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::lightspeed::devices::_ProtoDevice_default_instance_._instance,
};

const char descriptor_table_protodef_protocol_2fdevices_2fdevice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035protocol/devices/device.proto\022\022lightsp"
  "eed.devices\032\037protocol/properties/props.p"
  "roto\"\372\001\n\013ProtoDevice\022\n\n\002id\030\001 \001(\t\022\014\n\004name"
  "\030\002 \001(\t\022.\n\nproperties\030\003 \003(\0132\032.lightspeed."
  "props.Property\022\017\n\007address\030\004 \001(\t\022\014\n\004baud\030"
  "\005 \001(\005\0226\n\006family\030\006 \001(\0162&.lightspeed.devic"
  "es.ProtoDevice.Family\"J\n\006Family\022\007\n\003CCD\020\000"
  "\022\t\n\005MOUNT\020\001\022\013\n\007FOCUSER\020\002\022\020\n\014FILTER_WHEEL"
  "\020\003\022\r\n\tPOWER_BOX\020\004P\000b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_protocol_2fdevices_2fdevice_2eproto_deps[1] = {
  &::descriptor_table_protocol_2fproperties_2fprops_2eproto,
};
static ::_pbi::once_flag descriptor_table_protocol_2fdevices_2fdevice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_protocol_2fdevices_2fdevice_2eproto = {
    false, false, 347, descriptor_table_protodef_protocol_2fdevices_2fdevice_2eproto,
    "protocol/devices/device.proto",
    &descriptor_table_protocol_2fdevices_2fdevice_2eproto_once, descriptor_table_protocol_2fdevices_2fdevice_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_protocol_2fdevices_2fdevice_2eproto::offsets,
    file_level_metadata_protocol_2fdevices_2fdevice_2eproto, file_level_enum_descriptors_protocol_2fdevices_2fdevice_2eproto,
    file_level_service_descriptors_protocol_2fdevices_2fdevice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_protocol_2fdevices_2fdevice_2eproto_getter() {
  return &descriptor_table_protocol_2fdevices_2fdevice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_protocol_2fdevices_2fdevice_2eproto(&descriptor_table_protocol_2fdevices_2fdevice_2eproto);
namespace lightspeed {
namespace devices {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ProtoDevice_Family_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_protocol_2fdevices_2fdevice_2eproto);
  return file_level_enum_descriptors_protocol_2fdevices_2fdevice_2eproto[0];
}
bool ProtoDevice_Family_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr ProtoDevice_Family ProtoDevice::CCD;
constexpr ProtoDevice_Family ProtoDevice::MOUNT;
constexpr ProtoDevice_Family ProtoDevice::FOCUSER;
constexpr ProtoDevice_Family ProtoDevice::FILTER_WHEEL;
constexpr ProtoDevice_Family ProtoDevice::POWER_BOX;
constexpr ProtoDevice_Family ProtoDevice::Family_MIN;
constexpr ProtoDevice_Family ProtoDevice::Family_MAX;
constexpr int ProtoDevice::Family_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class ProtoDevice::_Internal {
 public:
};

void ProtoDevice::clear_properties() {
  properties_.Clear();
}
ProtoDevice::ProtoDevice(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  properties_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:lightspeed.devices.ProtoDevice)
}
ProtoDevice::ProtoDevice(const ProtoDevice& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      properties_(from.properties_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_id().empty()) {
    id_.Set(from._internal_id(), 
      GetArenaForAllocation());
  }
  name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    name_.Set(from._internal_name(), 
      GetArenaForAllocation());
  }
  address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_address().empty()) {
    address_.Set(from._internal_address(), 
      GetArenaForAllocation());
  }
  ::memcpy(&baud_, &from.baud_,
    static_cast<size_t>(reinterpret_cast<char*>(&family_) -
    reinterpret_cast<char*>(&baud_)) + sizeof(family_));
  // @@protoc_insertion_point(copy_constructor:lightspeed.devices.ProtoDevice)
}

inline void ProtoDevice::SharedCtor() {
id_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  id_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
name_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  name_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
address_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  address_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&baud_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&family_) -
    reinterpret_cast<char*>(&baud_)) + sizeof(family_));
}

ProtoDevice::~ProtoDevice() {
  // @@protoc_insertion_point(destructor:lightspeed.devices.ProtoDevice)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProtoDevice::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  id_.Destroy();
  name_.Destroy();
  address_.Destroy();
}

void ProtoDevice::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ProtoDevice::Clear() {
// @@protoc_insertion_point(message_clear_start:lightspeed.devices.ProtoDevice)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  properties_.Clear();
  id_.ClearToEmpty();
  name_.ClearToEmpty();
  address_.ClearToEmpty();
  ::memset(&baud_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&family_) -
      reinterpret_cast<char*>(&baud_)) + sizeof(family_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProtoDevice::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lightspeed.devices.ProtoDevice.id"));
        } else
          goto handle_unusual;
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lightspeed.devices.ProtoDevice.name"));
        } else
          goto handle_unusual;
        continue;
      // repeated .lightspeed.props.Property properties = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_properties(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string address = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lightspeed.devices.ProtoDevice.address"));
        } else
          goto handle_unusual;
        continue;
      // int32 baud = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          baud_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .lightspeed.devices.ProtoDevice.Family family = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_family(static_cast<::lightspeed::devices::ProtoDevice_Family>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProtoDevice::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lightspeed.devices.ProtoDevice)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lightspeed.devices.ProtoDevice.id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lightspeed.devices.ProtoDevice.name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  // repeated .lightspeed.props.Property properties = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_properties_size()); i < n; i++) {
    const auto& repfield = this->_internal_properties(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  // string address = 4;
  if (!this->_internal_address().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_address().data(), static_cast<int>(this->_internal_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lightspeed.devices.ProtoDevice.address");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_address(), target);
  }

  // int32 baud = 5;
  if (this->_internal_baud() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_baud(), target);
  }

  // .lightspeed.devices.ProtoDevice.Family family = 6;
  if (this->_internal_family() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      6, this->_internal_family(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lightspeed.devices.ProtoDevice)
  return target;
}

size_t ProtoDevice::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lightspeed.devices.ProtoDevice)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .lightspeed.props.Property properties = 3;
  total_size += 1UL * this->_internal_properties_size();
  for (const auto& msg : this->properties_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string id = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string address = 4;
  if (!this->_internal_address().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_address());
  }

  // int32 baud = 5;
  if (this->_internal_baud() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_baud());
  }

  // .lightspeed.devices.ProtoDevice.Family family = 6;
  if (this->_internal_family() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_family());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProtoDevice::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ProtoDevice::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProtoDevice::GetClassData() const { return &_class_data_; }

void ProtoDevice::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ProtoDevice *>(to)->MergeFrom(
      static_cast<const ProtoDevice &>(from));
}


void ProtoDevice::MergeFrom(const ProtoDevice& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:lightspeed.devices.ProtoDevice)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  properties_.MergeFrom(from.properties_);
  if (!from._internal_id().empty()) {
    _internal_set_id(from._internal_id());
  }
  if (!from._internal_name().empty()) {
    _internal_set_name(from._internal_name());
  }
  if (!from._internal_address().empty()) {
    _internal_set_address(from._internal_address());
  }
  if (from._internal_baud() != 0) {
    _internal_set_baud(from._internal_baud());
  }
  if (from._internal_family() != 0) {
    _internal_set_family(from._internal_family());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProtoDevice::CopyFrom(const ProtoDevice& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lightspeed.devices.ProtoDevice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtoDevice::IsInitialized() const {
  return true;
}

void ProtoDevice::InternalSwap(ProtoDevice* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  properties_.InternalSwap(&other->properties_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &id_, lhs_arena,
      &other->id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &name_, lhs_arena,
      &other->name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &address_, lhs_arena,
      &other->address_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtoDevice, family_)
      + sizeof(ProtoDevice::family_)
      - PROTOBUF_FIELD_OFFSET(ProtoDevice, baud_)>(
          reinterpret_cast<char*>(&baud_),
          reinterpret_cast<char*>(&other->baud_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtoDevice::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_protocol_2fdevices_2fdevice_2eproto_getter, &descriptor_table_protocol_2fdevices_2fdevice_2eproto_once,
      file_level_metadata_protocol_2fdevices_2fdevice_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace devices
}  // namespace lightspeed
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::lightspeed::devices::ProtoDevice*
Arena::CreateMaybeMessage< ::lightspeed::devices::ProtoDevice >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lightspeed::devices::ProtoDevice >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
