// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: devices/actions.proto

#include "devices/actions.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace lightspeed {
namespace devices {
namespace actions {
}  // namespace actions
}  // namespace devices
}  // namespace lightspeed
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_devices_2factions_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_devices_2factions_2eproto = nullptr;
const uint32_t TableStruct_devices_2factions_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_devices_2factions_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025devices/actions.proto\022\032lightspeed.devi"
  "ces.actions*\216\001\n\rDeviceActions\022\006\n\002Ok\020\000\022\021\n"
  "\rCannotConnect\020\001\022\014\n\010ComError\020\002\022\013\n\007Timeou"
  "t\020\003\022 \n\034CannotUpdateReadOnlyProperty\020\004\022\023\n"
  "\017UnknownProperty\020\005\022\020\n\014InvalidValue\020\006b\006pr"
  "oto3"
  ;
static ::_pbi::once_flag descriptor_table_devices_2factions_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_devices_2factions_2eproto = {
    false, false, 204, descriptor_table_protodef_devices_2factions_2eproto,
    "devices/actions.proto",
    &descriptor_table_devices_2factions_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_devices_2factions_2eproto::offsets,
    nullptr, file_level_enum_descriptors_devices_2factions_2eproto,
    file_level_service_descriptors_devices_2factions_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_devices_2factions_2eproto_getter() {
  return &descriptor_table_devices_2factions_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_devices_2factions_2eproto(&descriptor_table_devices_2factions_2eproto);
namespace lightspeed {
namespace devices {
namespace actions {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DeviceActions_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_devices_2factions_2eproto);
  return file_level_enum_descriptors_devices_2factions_2eproto[0];
}
bool DeviceActions_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace actions
}  // namespace devices
}  // namespace lightspeed
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
