// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/main/response.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2fmain_2fresponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2fmain_2fresponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "protocol/properties/props.pb.h"
#include "protocol/devices/device.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2fmain_2fresponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fmain_2fresponse_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protocol_2fmain_2fresponse_2eproto;
namespace lightspeed {
namespace response {
class GetDeviceResponse;
struct GetDeviceResponseDefaultTypeInternal;
extern GetDeviceResponseDefaultTypeInternal _GetDeviceResponse_default_instance_;
class GetDevicesResponse;
struct GetDevicesResponseDefaultTypeInternal;
extern GetDevicesResponseDefaultTypeInternal _GetDevicesResponse_default_instance_;
class GetPropertiesResponse;
struct GetPropertiesResponseDefaultTypeInternal;
extern GetPropertiesResponseDefaultTypeInternal _GetPropertiesResponse_default_instance_;
}  // namespace response
}  // namespace lightspeed
PROTOBUF_NAMESPACE_OPEN
template<> ::lightspeed::response::GetDeviceResponse* Arena::CreateMaybeMessage<::lightspeed::response::GetDeviceResponse>(Arena*);
template<> ::lightspeed::response::GetDevicesResponse* Arena::CreateMaybeMessage<::lightspeed::response::GetDevicesResponse>(Arena*);
template<> ::lightspeed::response::GetPropertiesResponse* Arena::CreateMaybeMessage<::lightspeed::response::GetPropertiesResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace lightspeed {
namespace response {

// ===================================================================

class GetPropertiesResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lightspeed.response.GetPropertiesResponse) */ {
 public:
  inline GetPropertiesResponse() : GetPropertiesResponse(nullptr) {}
  ~GetPropertiesResponse() override;
  explicit PROTOBUF_CONSTEXPR GetPropertiesResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetPropertiesResponse(const GetPropertiesResponse& from);
  GetPropertiesResponse(GetPropertiesResponse&& from) noexcept
    : GetPropertiesResponse() {
    *this = ::std::move(from);
  }

  inline GetPropertiesResponse& operator=(const GetPropertiesResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetPropertiesResponse& operator=(GetPropertiesResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetPropertiesResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetPropertiesResponse* internal_default_instance() {
    return reinterpret_cast<const GetPropertiesResponse*>(
               &_GetPropertiesResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetPropertiesResponse& a, GetPropertiesResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetPropertiesResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetPropertiesResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetPropertiesResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetPropertiesResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetPropertiesResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetPropertiesResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetPropertiesResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lightspeed.response.GetPropertiesResponse";
  }
  protected:
  explicit GetPropertiesResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPropertiesFieldNumber = 2,
    kDeviceNameFieldNumber = 1,
  };
  // repeated .lightspeed.props.Property properties = 2;
  int properties_size() const;
  private:
  int _internal_properties_size() const;
  public:
  void clear_properties();
  ::lightspeed::props::Property* mutable_properties(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lightspeed::props::Property >*
      mutable_properties();
  private:
  const ::lightspeed::props::Property& _internal_properties(int index) const;
  ::lightspeed::props::Property* _internal_add_properties();
  public:
  const ::lightspeed::props::Property& properties(int index) const;
  ::lightspeed::props::Property* add_properties();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lightspeed::props::Property >&
      properties() const;

  // string device_name = 1;
  void clear_device_name();
  const std::string& device_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_device_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_device_name();
  PROTOBUF_NODISCARD std::string* release_device_name();
  void set_allocated_device_name(std::string* device_name);
  private:
  const std::string& _internal_device_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_device_name(const std::string& value);
  std::string* _internal_mutable_device_name();
  public:

  // @@protoc_insertion_point(class_scope:lightspeed.response.GetPropertiesResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lightspeed::props::Property > properties_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr device_name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fmain_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class GetDeviceResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lightspeed.response.GetDeviceResponse) */ {
 public:
  inline GetDeviceResponse() : GetDeviceResponse(nullptr) {}
  ~GetDeviceResponse() override;
  explicit PROTOBUF_CONSTEXPR GetDeviceResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetDeviceResponse(const GetDeviceResponse& from);
  GetDeviceResponse(GetDeviceResponse&& from) noexcept
    : GetDeviceResponse() {
    *this = ::std::move(from);
  }

  inline GetDeviceResponse& operator=(const GetDeviceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetDeviceResponse& operator=(GetDeviceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetDeviceResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetDeviceResponse* internal_default_instance() {
    return reinterpret_cast<const GetDeviceResponse*>(
               &_GetDeviceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetDeviceResponse& a, GetDeviceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetDeviceResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetDeviceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetDeviceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetDeviceResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetDeviceResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetDeviceResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetDeviceResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lightspeed.response.GetDeviceResponse";
  }
  protected:
  explicit GetDeviceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeviceFieldNumber = 1,
  };
  // .lightspeed.devices.ProtoDevice device = 1;
  bool has_device() const;
  private:
  bool _internal_has_device() const;
  public:
  void clear_device();
  const ::lightspeed::devices::ProtoDevice& device() const;
  PROTOBUF_NODISCARD ::lightspeed::devices::ProtoDevice* release_device();
  ::lightspeed::devices::ProtoDevice* mutable_device();
  void set_allocated_device(::lightspeed::devices::ProtoDevice* device);
  private:
  const ::lightspeed::devices::ProtoDevice& _internal_device() const;
  ::lightspeed::devices::ProtoDevice* _internal_mutable_device();
  public:
  void unsafe_arena_set_allocated_device(
      ::lightspeed::devices::ProtoDevice* device);
  ::lightspeed::devices::ProtoDevice* unsafe_arena_release_device();

  // @@protoc_insertion_point(class_scope:lightspeed.response.GetDeviceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::lightspeed::devices::ProtoDevice* device_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fmain_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class GetDevicesResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lightspeed.response.GetDevicesResponse) */ {
 public:
  inline GetDevicesResponse() : GetDevicesResponse(nullptr) {}
  ~GetDevicesResponse() override;
  explicit PROTOBUF_CONSTEXPR GetDevicesResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetDevicesResponse(const GetDevicesResponse& from);
  GetDevicesResponse(GetDevicesResponse&& from) noexcept
    : GetDevicesResponse() {
    *this = ::std::move(from);
  }

  inline GetDevicesResponse& operator=(const GetDevicesResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetDevicesResponse& operator=(GetDevicesResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetDevicesResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetDevicesResponse* internal_default_instance() {
    return reinterpret_cast<const GetDevicesResponse*>(
               &_GetDevicesResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetDevicesResponse& a, GetDevicesResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetDevicesResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetDevicesResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetDevicesResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetDevicesResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetDevicesResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetDevicesResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetDevicesResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lightspeed.response.GetDevicesResponse";
  }
  protected:
  explicit GetDevicesResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDevicesFieldNumber = 1,
  };
  // repeated .lightspeed.devices.ProtoDevice devices = 1;
  int devices_size() const;
  private:
  int _internal_devices_size() const;
  public:
  void clear_devices();
  ::lightspeed::devices::ProtoDevice* mutable_devices(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lightspeed::devices::ProtoDevice >*
      mutable_devices();
  private:
  const ::lightspeed::devices::ProtoDevice& _internal_devices(int index) const;
  ::lightspeed::devices::ProtoDevice* _internal_add_devices();
  public:
  const ::lightspeed::devices::ProtoDevice& devices(int index) const;
  ::lightspeed::devices::ProtoDevice* add_devices();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lightspeed::devices::ProtoDevice >&
      devices() const;

  // @@protoc_insertion_point(class_scope:lightspeed.response.GetDevicesResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lightspeed::devices::ProtoDevice > devices_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fmain_2fresponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetPropertiesResponse

// string device_name = 1;
inline void GetPropertiesResponse::clear_device_name() {
  device_name_.ClearToEmpty();
}
inline const std::string& GetPropertiesResponse::device_name() const {
  // @@protoc_insertion_point(field_get:lightspeed.response.GetPropertiesResponse.device_name)
  return _internal_device_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetPropertiesResponse::set_device_name(ArgT0&& arg0, ArgT... args) {
 
 device_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lightspeed.response.GetPropertiesResponse.device_name)
}
inline std::string* GetPropertiesResponse::mutable_device_name() {
  std::string* _s = _internal_mutable_device_name();
  // @@protoc_insertion_point(field_mutable:lightspeed.response.GetPropertiesResponse.device_name)
  return _s;
}
inline const std::string& GetPropertiesResponse::_internal_device_name() const {
  return device_name_.Get();
}
inline void GetPropertiesResponse::_internal_set_device_name(const std::string& value) {
  
  device_name_.Set(value, GetArenaForAllocation());
}
inline std::string* GetPropertiesResponse::_internal_mutable_device_name() {
  
  return device_name_.Mutable(GetArenaForAllocation());
}
inline std::string* GetPropertiesResponse::release_device_name() {
  // @@protoc_insertion_point(field_release:lightspeed.response.GetPropertiesResponse.device_name)
  return device_name_.Release();
}
inline void GetPropertiesResponse::set_allocated_device_name(std::string* device_name) {
  if (device_name != nullptr) {
    
  } else {
    
  }
  device_name_.SetAllocated(device_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (device_name_.IsDefault()) {
    device_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lightspeed.response.GetPropertiesResponse.device_name)
}

// repeated .lightspeed.props.Property properties = 2;
inline int GetPropertiesResponse::_internal_properties_size() const {
  return properties_.size();
}
inline int GetPropertiesResponse::properties_size() const {
  return _internal_properties_size();
}
inline ::lightspeed::props::Property* GetPropertiesResponse::mutable_properties(int index) {
  // @@protoc_insertion_point(field_mutable:lightspeed.response.GetPropertiesResponse.properties)
  return properties_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lightspeed::props::Property >*
GetPropertiesResponse::mutable_properties() {
  // @@protoc_insertion_point(field_mutable_list:lightspeed.response.GetPropertiesResponse.properties)
  return &properties_;
}
inline const ::lightspeed::props::Property& GetPropertiesResponse::_internal_properties(int index) const {
  return properties_.Get(index);
}
inline const ::lightspeed::props::Property& GetPropertiesResponse::properties(int index) const {
  // @@protoc_insertion_point(field_get:lightspeed.response.GetPropertiesResponse.properties)
  return _internal_properties(index);
}
inline ::lightspeed::props::Property* GetPropertiesResponse::_internal_add_properties() {
  return properties_.Add();
}
inline ::lightspeed::props::Property* GetPropertiesResponse::add_properties() {
  ::lightspeed::props::Property* _add = _internal_add_properties();
  // @@protoc_insertion_point(field_add:lightspeed.response.GetPropertiesResponse.properties)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lightspeed::props::Property >&
GetPropertiesResponse::properties() const {
  // @@protoc_insertion_point(field_list:lightspeed.response.GetPropertiesResponse.properties)
  return properties_;
}

// -------------------------------------------------------------------

// GetDeviceResponse

// .lightspeed.devices.ProtoDevice device = 1;
inline bool GetDeviceResponse::_internal_has_device() const {
  return this != internal_default_instance() && device_ != nullptr;
}
inline bool GetDeviceResponse::has_device() const {
  return _internal_has_device();
}
inline const ::lightspeed::devices::ProtoDevice& GetDeviceResponse::_internal_device() const {
  const ::lightspeed::devices::ProtoDevice* p = device_;
  return p != nullptr ? *p : reinterpret_cast<const ::lightspeed::devices::ProtoDevice&>(
      ::lightspeed::devices::_ProtoDevice_default_instance_);
}
inline const ::lightspeed::devices::ProtoDevice& GetDeviceResponse::device() const {
  // @@protoc_insertion_point(field_get:lightspeed.response.GetDeviceResponse.device)
  return _internal_device();
}
inline void GetDeviceResponse::unsafe_arena_set_allocated_device(
    ::lightspeed::devices::ProtoDevice* device) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(device_);
  }
  device_ = device;
  if (device) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lightspeed.response.GetDeviceResponse.device)
}
inline ::lightspeed::devices::ProtoDevice* GetDeviceResponse::release_device() {
  
  ::lightspeed::devices::ProtoDevice* temp = device_;
  device_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::lightspeed::devices::ProtoDevice* GetDeviceResponse::unsafe_arena_release_device() {
  // @@protoc_insertion_point(field_release:lightspeed.response.GetDeviceResponse.device)
  
  ::lightspeed::devices::ProtoDevice* temp = device_;
  device_ = nullptr;
  return temp;
}
inline ::lightspeed::devices::ProtoDevice* GetDeviceResponse::_internal_mutable_device() {
  
  if (device_ == nullptr) {
    auto* p = CreateMaybeMessage<::lightspeed::devices::ProtoDevice>(GetArenaForAllocation());
    device_ = p;
  }
  return device_;
}
inline ::lightspeed::devices::ProtoDevice* GetDeviceResponse::mutable_device() {
  ::lightspeed::devices::ProtoDevice* _msg = _internal_mutable_device();
  // @@protoc_insertion_point(field_mutable:lightspeed.response.GetDeviceResponse.device)
  return _msg;
}
inline void GetDeviceResponse::set_allocated_device(::lightspeed::devices::ProtoDevice* device) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(device_);
  }
  if (device) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(device));
    if (message_arena != submessage_arena) {
      device = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, device, submessage_arena);
    }
    
  } else {
    
  }
  device_ = device;
  // @@protoc_insertion_point(field_set_allocated:lightspeed.response.GetDeviceResponse.device)
}

// -------------------------------------------------------------------

// GetDevicesResponse

// repeated .lightspeed.devices.ProtoDevice devices = 1;
inline int GetDevicesResponse::_internal_devices_size() const {
  return devices_.size();
}
inline int GetDevicesResponse::devices_size() const {
  return _internal_devices_size();
}
inline ::lightspeed::devices::ProtoDevice* GetDevicesResponse::mutable_devices(int index) {
  // @@protoc_insertion_point(field_mutable:lightspeed.response.GetDevicesResponse.devices)
  return devices_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lightspeed::devices::ProtoDevice >*
GetDevicesResponse::mutable_devices() {
  // @@protoc_insertion_point(field_mutable_list:lightspeed.response.GetDevicesResponse.devices)
  return &devices_;
}
inline const ::lightspeed::devices::ProtoDevice& GetDevicesResponse::_internal_devices(int index) const {
  return devices_.Get(index);
}
inline const ::lightspeed::devices::ProtoDevice& GetDevicesResponse::devices(int index) const {
  // @@protoc_insertion_point(field_get:lightspeed.response.GetDevicesResponse.devices)
  return _internal_devices(index);
}
inline ::lightspeed::devices::ProtoDevice* GetDevicesResponse::_internal_add_devices() {
  return devices_.Add();
}
inline ::lightspeed::devices::ProtoDevice* GetDevicesResponse::add_devices() {
  ::lightspeed::devices::ProtoDevice* _add = _internal_add_devices();
  // @@protoc_insertion_point(field_add:lightspeed.response.GetDevicesResponse.devices)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lightspeed::devices::ProtoDevice >&
GetDevicesResponse::devices() const {
  // @@protoc_insertion_point(field_list:lightspeed.response.GetDevicesResponse.devices)
  return devices_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace response
}  // namespace lightspeed

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2fmain_2fresponse_2eproto
