// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/main/response.proto

package lightspeed.response;

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetPropertiesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lightspeed.response.GetPropertiesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string device_name = 1;</code>
     * @return The deviceName.
     */
    java.lang.String getDeviceName();
    /**
     * <code>string device_name = 1;</code>
     * @return The bytes for deviceName.
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();

    /**
     * <code>repeated .lightspeed.props.Property properties = 2;</code>
     */
    java.util.List<lightspeed.props.Props.Property> 
        getPropertiesList();
    /**
     * <code>repeated .lightspeed.props.Property properties = 2;</code>
     */
    lightspeed.props.Props.Property getProperties(int index);
    /**
     * <code>repeated .lightspeed.props.Property properties = 2;</code>
     */
    int getPropertiesCount();
    /**
     * <code>repeated .lightspeed.props.Property properties = 2;</code>
     */
    java.util.List<? extends lightspeed.props.Props.PropertyOrBuilder> 
        getPropertiesOrBuilderList();
    /**
     * <code>repeated .lightspeed.props.Property properties = 2;</code>
     */
    lightspeed.props.Props.PropertyOrBuilder getPropertiesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code lightspeed.response.GetPropertiesResponse}
   */
  public static final class GetPropertiesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lightspeed.response.GetPropertiesResponse)
      GetPropertiesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetPropertiesResponse.newBuilder() to construct.
    private GetPropertiesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetPropertiesResponse() {
      deviceName_ = "";
      properties_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetPropertiesResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetPropertiesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceName_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                properties_ = new java.util.ArrayList<lightspeed.props.Props.Property>();
                mutable_bitField0_ |= 0x00000001;
              }
              properties_.add(
                  input.readMessage(lightspeed.props.Props.Property.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          properties_ = java.util.Collections.unmodifiableList(properties_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lightspeed.response.Response.internal_static_lightspeed_response_GetPropertiesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lightspeed.response.Response.internal_static_lightspeed_response_GetPropertiesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lightspeed.response.Response.GetPropertiesResponse.class, lightspeed.response.Response.GetPropertiesResponse.Builder.class);
    }

    public static final int DEVICE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceName_;
    /**
     * <code>string device_name = 1;</code>
     * @return The deviceName.
     */
    @java.lang.Override
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string device_name = 1;</code>
     * @return The bytes for deviceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROPERTIES_FIELD_NUMBER = 2;
    private java.util.List<lightspeed.props.Props.Property> properties_;
    /**
     * <code>repeated .lightspeed.props.Property properties = 2;</code>
     */
    @java.lang.Override
    public java.util.List<lightspeed.props.Props.Property> getPropertiesList() {
      return properties_;
    }
    /**
     * <code>repeated .lightspeed.props.Property properties = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends lightspeed.props.Props.PropertyOrBuilder> 
        getPropertiesOrBuilderList() {
      return properties_;
    }
    /**
     * <code>repeated .lightspeed.props.Property properties = 2;</code>
     */
    @java.lang.Override
    public int getPropertiesCount() {
      return properties_.size();
    }
    /**
     * <code>repeated .lightspeed.props.Property properties = 2;</code>
     */
    @java.lang.Override
    public lightspeed.props.Props.Property getProperties(int index) {
      return properties_.get(index);
    }
    /**
     * <code>repeated .lightspeed.props.Property properties = 2;</code>
     */
    @java.lang.Override
    public lightspeed.props.Props.PropertyOrBuilder getPropertiesOrBuilder(
        int index) {
      return properties_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceName_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        output.writeMessage(2, properties_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceName_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, properties_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lightspeed.response.Response.GetPropertiesResponse)) {
        return super.equals(obj);
      }
      lightspeed.response.Response.GetPropertiesResponse other = (lightspeed.response.Response.GetPropertiesResponse) obj;

      if (!getDeviceName()
          .equals(other.getDeviceName())) return false;
      if (!getPropertiesList()
          .equals(other.getPropertiesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceName().hashCode();
      if (getPropertiesCount() > 0) {
        hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
        hash = (53 * hash) + getPropertiesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lightspeed.response.Response.GetPropertiesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lightspeed.response.Response.GetPropertiesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lightspeed.response.Response.GetPropertiesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lightspeed.response.Response.GetPropertiesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lightspeed.response.Response.GetPropertiesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lightspeed.response.Response.GetPropertiesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lightspeed.response.Response.GetPropertiesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lightspeed.response.Response.GetPropertiesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static lightspeed.response.Response.GetPropertiesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static lightspeed.response.Response.GetPropertiesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lightspeed.response.Response.GetPropertiesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lightspeed.response.Response.GetPropertiesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lightspeed.response.Response.GetPropertiesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lightspeed.response.GetPropertiesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lightspeed.response.GetPropertiesResponse)
        lightspeed.response.Response.GetPropertiesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lightspeed.response.Response.internal_static_lightspeed_response_GetPropertiesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lightspeed.response.Response.internal_static_lightspeed_response_GetPropertiesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lightspeed.response.Response.GetPropertiesResponse.class, lightspeed.response.Response.GetPropertiesResponse.Builder.class);
      }

      // Construct using lightspeed.response.Response.GetPropertiesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPropertiesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceName_ = "";

        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lightspeed.response.Response.internal_static_lightspeed_response_GetPropertiesResponse_descriptor;
      }

      @java.lang.Override
      public lightspeed.response.Response.GetPropertiesResponse getDefaultInstanceForType() {
        return lightspeed.response.Response.GetPropertiesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public lightspeed.response.Response.GetPropertiesResponse build() {
        lightspeed.response.Response.GetPropertiesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lightspeed.response.Response.GetPropertiesResponse buildPartial() {
        lightspeed.response.Response.GetPropertiesResponse result = new lightspeed.response.Response.GetPropertiesResponse(this);
        int from_bitField0_ = bitField0_;
        result.deviceName_ = deviceName_;
        if (propertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            properties_ = java.util.Collections.unmodifiableList(properties_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.properties_ = properties_;
        } else {
          result.properties_ = propertiesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lightspeed.response.Response.GetPropertiesResponse) {
          return mergeFrom((lightspeed.response.Response.GetPropertiesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lightspeed.response.Response.GetPropertiesResponse other) {
        if (other == lightspeed.response.Response.GetPropertiesResponse.getDefaultInstance()) return this;
        if (!other.getDeviceName().isEmpty()) {
          deviceName_ = other.deviceName_;
          onChanged();
        }
        if (propertiesBuilder_ == null) {
          if (!other.properties_.isEmpty()) {
            if (properties_.isEmpty()) {
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePropertiesIsMutable();
              properties_.addAll(other.properties_);
            }
            onChanged();
          }
        } else {
          if (!other.properties_.isEmpty()) {
            if (propertiesBuilder_.isEmpty()) {
              propertiesBuilder_.dispose();
              propertiesBuilder_ = null;
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000001);
              propertiesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPropertiesFieldBuilder() : null;
            } else {
              propertiesBuilder_.addAllMessages(other.properties_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        lightspeed.response.Response.GetPropertiesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (lightspeed.response.Response.GetPropertiesResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object deviceName_ = "";
      /**
       * <code>string device_name = 1;</code>
       * @return The deviceName.
       */
      public java.lang.String getDeviceName() {
        java.lang.Object ref = deviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_name = 1;</code>
       * @return The bytes for deviceName.
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        java.lang.Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_name = 1;</code>
       * @param value The deviceName to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string device_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceName() {
        
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>string device_name = 1;</code>
       * @param value The bytes for deviceName to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<lightspeed.props.Props.Property> properties_ =
        java.util.Collections.emptyList();
      private void ensurePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          properties_ = new java.util.ArrayList<lightspeed.props.Props.Property>(properties_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          lightspeed.props.Props.Property, lightspeed.props.Props.Property.Builder, lightspeed.props.Props.PropertyOrBuilder> propertiesBuilder_;

      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public java.util.List<lightspeed.props.Props.Property> getPropertiesList() {
        if (propertiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(properties_);
        } else {
          return propertiesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public int getPropertiesCount() {
        if (propertiesBuilder_ == null) {
          return properties_.size();
        } else {
          return propertiesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public lightspeed.props.Props.Property getProperties(int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);
        } else {
          return propertiesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public Builder setProperties(
          int index, lightspeed.props.Props.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.set(index, value);
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public Builder setProperties(
          int index, lightspeed.props.Props.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public Builder addProperties(lightspeed.props.Props.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public Builder addProperties(
          int index, lightspeed.props.Props.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(index, value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public Builder addProperties(
          lightspeed.props.Props.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public Builder addProperties(
          int index, lightspeed.props.Props.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public Builder addAllProperties(
          java.lang.Iterable<? extends lightspeed.props.Props.Property> values) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, properties_);
          onChanged();
        } else {
          propertiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public Builder clearProperties() {
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public Builder removeProperties(int index) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.remove(index);
          onChanged();
        } else {
          propertiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public lightspeed.props.Props.Property.Builder getPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public lightspeed.props.Props.PropertyOrBuilder getPropertiesOrBuilder(
          int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);  } else {
          return propertiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public java.util.List<? extends lightspeed.props.Props.PropertyOrBuilder> 
           getPropertiesOrBuilderList() {
        if (propertiesBuilder_ != null) {
          return propertiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(properties_);
        }
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public lightspeed.props.Props.Property.Builder addPropertiesBuilder() {
        return getPropertiesFieldBuilder().addBuilder(
            lightspeed.props.Props.Property.getDefaultInstance());
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public lightspeed.props.Props.Property.Builder addPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().addBuilder(
            index, lightspeed.props.Props.Property.getDefaultInstance());
      }
      /**
       * <code>repeated .lightspeed.props.Property properties = 2;</code>
       */
      public java.util.List<lightspeed.props.Props.Property.Builder> 
           getPropertiesBuilderList() {
        return getPropertiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          lightspeed.props.Props.Property, lightspeed.props.Props.Property.Builder, lightspeed.props.Props.PropertyOrBuilder> 
          getPropertiesFieldBuilder() {
        if (propertiesBuilder_ == null) {
          propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              lightspeed.props.Props.Property, lightspeed.props.Props.Property.Builder, lightspeed.props.Props.PropertyOrBuilder>(
                  properties_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          properties_ = null;
        }
        return propertiesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lightspeed.response.GetPropertiesResponse)
    }

    // @@protoc_insertion_point(class_scope:lightspeed.response.GetPropertiesResponse)
    private static final lightspeed.response.Response.GetPropertiesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lightspeed.response.Response.GetPropertiesResponse();
    }

    public static lightspeed.response.Response.GetPropertiesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetPropertiesResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetPropertiesResponse>() {
      @java.lang.Override
      public GetPropertiesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetPropertiesResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetPropertiesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetPropertiesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lightspeed.response.Response.GetPropertiesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightspeed_response_GetPropertiesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightspeed_response_GetPropertiesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034protocol/main/response.proto\022\023lightspe" +
      "ed.response\032\037protocol/properties/props.p" +
      "roto\"\\\n\025GetPropertiesResponse\022\023\n\013device_" +
      "name\030\001 \001(\t\022.\n\nproperties\030\002 \003(\0132\032.lightsp" +
      "eed.props.PropertyP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          lightspeed.props.Props.getDescriptor(),
        });
    internal_static_lightspeed_response_GetPropertiesResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightspeed_response_GetPropertiesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightspeed_response_GetPropertiesResponse_descriptor,
        new java.lang.String[] { "DeviceName", "Properties", });
    lightspeed.props.Props.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
